import type { InferGetServerSidePropsType, GetServerSideProps } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'


const inter = Inter({ subsets: ['latin'] })

type IAPIResponse = {
  counter: number
  dataURL: string
}
 
export const getServerSideProps: GetServerSideProps<{
  apiResponse: IAPIResponse
}> = async () => {
  const res = await fetch('http://localhost:3000/api/counter')
  const apiResponse = await res.json()
  console.log(apiResponse)
  return { props: { apiResponse } }
} 

export default function Home({
  apiResponse,
}: InferGetServerSidePropsType<typeof getServerSideProps>) {
  return (
    <>
      <Head>
        <title>Generic counter</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>
        <div className={styles.description}>
          <p>
            <Image
                src={apiResponse.dataURL}
                alt="Vercel Logo"
                className={styles.vercelLogo}
                width={400}
                height={40}
                priority
              />
          </p>
        </div>
      </main>
    </>
  )
}
